version: '3.8'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: siknusa-backend-app
    container_name: siknusa-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - siknusa-network

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: siknusa-web
    restart: unless-stopped
    tty: true
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - siknusa-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: siknusa-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - siknusa-dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - siknusa-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: siknusa-phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    networks:
      - siknusa-network
    depends_on:
      - db

networks:
  siknusa-network:
    driver: bridge

volumes:
  siknusa-dbdata:
    driver: local
